development:
  adapter: postgresql
  encoding: utf8
  database: blog_development
  pool: 5
  template: template0

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: blog_test
  pool: 5
  template: template0

production:
  adapter: postgresql
  encoding: utf8
  database: blog_production
  pool: 5
  template: template0

cucumber:
  <<: *TEST
