development:
  adapter: sqlite3
  encoding: utf8
  database: cree_development
  pool: 5
  template: template0

test: &TEST
  adapter: sqlite3
  encoding: utf8
  database: cree_test
  pool: 5
  template: template0

production:
  adapter: postgresql
  encoding: utf8
  database: cree_production
  pool: 5
  template: template0

cucumber:
  <<: *TEST