# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a06c47fdd0fa19050b86c196bad0bee77da34870e146bc9c4496296d5b410de2469a4b73590a4fd2090c0554f249f0b27e5fd1a1463e75939923563d33e2f917


test:
  secret_key_base: af4bc244f775d2872ace944ea761f4f0793dbc33ed989abe04f1e95581fdf2cac4ca5e8226845fb23ce8dfcd775848a533c91dbfb02b5734f3af3c8eee16d700

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
